// Actions
export const SESSION_CONNECT_TO_WEB3 = 'SESSION_CONNECT_TO_WEB3';
export const SESSION_GET_BALANCE = 'SESSION_GET_BALANCE';

export const PIGGY_BANK_GET_BALANCE = 'PIGGY_BANK_GET_BALANCE';
export const PIGGY_BANK_GET_OWNER = 'PIGGY_BANK_GET_OWNER';
export const PIGGY_BANK_WITHDRAW = 'PIGGY_BANK_WITHDRAW';
export const PIGGY_BANK_DEPOSIT = 'PIGGY_BANK_DEPOSIT';

// Mutations
export const SESSION_SET_PROPERTY = 'SESSION_SET_PROPERTY';

export const PIGGY_BANK_SET_PROPERTY = 'PIGGY_BANK_SET_PROPERTY';

// Getters
export const SESSION_IS_LOGGED = 'SESSION_IS_LOGGED';
